#//////////////////////////////////////////////////////////////////////////////#
#///                    BATCHED INFLUENCE AND TAU SOLVER                     ///#
#//////////////////////////////////////////////////////////////////////////////#

"""
    BatchedInfluenceSolver(Ny, k, l, nu, lambda)

Factor independent nonzero Fourier-mode Stokes systems. Each row of the
input/output matrices is one system; columns contain ordinary Chebyshev
coefficients. `k` and `l` contain physical wavenumbers in the same row order.

The pressure boundary values are determined by an influence matrix imposing
zero normal-velocity derivatives at both walls. Gibson's tau correction
then cancels the divergence generated by the highest momentum residuals.
The factors and homogeneous responses are reused across solves.
"""
struct BatchedInfluenceSolver{H, A, V, C}
    pressure::H
    velocity::H
    responses::NTuple{6, A} # p+, p-, v+, v-, p0, v0
    influence::NTuple{4, V} # inverse 2×2 matrix in row-major order
    sigma::NTuple{2, V}     # auxiliary tau residuals
    shift::V
    k::V
    l::V
    boundary::V            # reusable zero wall data
    work::NTuple{2, C}     # complex pressure/velocity right-hand sides
end

# Differentiate whole batches. Each inner traversal covers contiguous systems;
# the recurrence only couples Chebyshev coefficients within a row.
function _batchdiff!(out::AbstractMatrix, a::AbstractMatrix)
    B, Ny = size(a)
    @views out[:, Ny] .= 0
    @views out[:, Ny-1] .= 2(Ny-1) .* a[:, Ny]
    @inbounds for j = Ny-2:-1:1
        @simd for s = 1:B
            out[s,j] = out[s,j+2] + 2j*a[s,j+1]
        end
    end
    @views out[:,1] .*= 0.5
    return out
end

function BatchedInfluenceSolver(Ny::Int, k::Vector{Float64}, l::Vector{Float64}, nu, lambda)
    isodd(Ny) && Ny ≥ 5 || throw(ArgumentError("tau correction requires odd Ny ≥ 5"))
    length(k) == length(l) || throw(DimensionMismatch("wavenumber vectors must match"))
    B = length(k)
    κ² = k.^2 .+ l.^2
    # A zero-mode pressure placeholder is overwritten by the mean-mode solve.
    shift = lambda .+ nu .* κ²
    ph = BatchedHelmoltzSolver(Ny-1, B)
    vh = BatchedHelmoltzSolver(Ny-1, B)
    update!(ph, ones(B), ifelse.(iszero.(κ²), 1.0, κ²))
    update!(vh, fill(Float64(nu), B), shift)
    responses = ntuple(_ -> zeros(B, Ny), 6)
    pp, pm, vp, vm, p0, v0 = responses
    work = zeros(B, Ny)
    zero_bc, unit_bc = zeros(B), ones(B)
    solve!(ph, pp, work, unit_bc, zero_bc)
    _batchdiff!(work, pp)
    solve!(vh, vp, work, zero_bc, zero_bc)
    fill!(work, 0)
    solve!(ph, pm, work, zero_bc, unit_bc)
    _batchdiff!(work, pm)
    solve!(vh, vm, work, zero_bc, zero_bc)

    influence = ntuple(_ -> zeros(B), 4)
    for s = 1:B
        a, b = diff(view(vp,s,:), :right), diff(view(vm,s,:), :right)
        c, d = diff(view(vp,s,:), :left), diff(view(vm,s,:), :left)
        scale = max(abs(a),abs(b),abs(c),abs(d))
        a,b,c,d = (a,b,c,d) ./ scale
        determinant = a*d-b*c
        isfinite(determinant) && abs(determinant) > eps()*max(abs(a*d),abs(b*c)) ||
            throw(ArgumentError("singular influence matrix for system $s"))
        for (dest, value) in zip(influence, (d,-b,-c,a))
            dest[s] = value/(determinant*scale)
        end
    end
    solver = BatchedInfluenceSolver(ph, vh, responses, influence,
        (zeros(B),zeros(B)), shift, copy(k), copy(l), zero_bc,
        (zeros(ComplexF64,B,Ny),zeros(ComplexF64,B,Ny)))

    # Both parities share one auxiliary problem: source (T_{P-1}+T_P)'.
    fill!(work,0)
    @views work[:,Ny-1:Ny] .= 1
    forcing = similar(work)
    _batchdiff!(forcing, work)
    solve!(ph,p0,forcing,zero_bc,zero_bc)
    _batchdiff!(forcing,p0)
    solve!(vh,v0,forcing,zero_bc,zero_bc)
    _batchinfluence!(solver,p0,v0)
    _batchdiff!(forcing,p0)
    @views solver.sigma[1] .= shift .* v0[:,Ny-1] .+ forcing[:,Ny-1]
    @views solver.sigma[2] .= shift .* v0[:,Ny]
    return solver
end

# The two wall residuals determine two homogeneous pressure amplitudes.
function _batchinfluence!(h::BatchedInfluenceSolver, p, v)
    pp,pm,vp,vm = h.responses
    a,b,c,d = h.influence
    B,Ny = size(p)
    @inbounds for s = 1:B
        upper = zero(eltype(v)); lower = zero(eltype(v))
        for j = 2:Ny
            term = (j-1)^2*v[s,j]
            upper -= term
            lower -= (iseven(j) ? 1 : -1)*term
        end
        δp = a[s]*upper+b[s]*lower
        δm = c[s]*upper+d[s]*lower
        for j = 1:Ny
            p[s,j] += δp*pp[s,j]+δm*pm[s,j]
            v[s,j] += δp*vp[s,j]+δm*vm[s,j]
        end
    end
    return nothing
end

"""
    solve!(h::BatchedInfluenceSolver, u, v, w, p, Rx, Ry, Rz)

Solve `(lambda + nu*k² - nu*D²)U + grad(p) = R`, `div(U)=0`,
with homogeneous no-slip walls. Matrices have size `(B, Ny)`; sources are
preserved and output storage must be distinct from the sources and caches.
"""
function solve!(h::BatchedInfluenceSolver, u, v, w, p, Rx, Ry, Rz)
    r,q = h.work
    bc = h.boundary
    _batchdiff!(r,Ry)
    r .+= im .* h.k .* Rx .+ im .* h.l .* Rz
    solve!(h.pressure,p,r,bc,bc)
    _batchdiff!(q,p)
    q .-= Ry
    solve!(h.velocity,v,q,bc,bc)
    _batchinfluence!(h,p,v)
    _batchdiff!(q,p)
    _batchtau!(h,p,v,q,Ry)
    r .= im .* h.k .* p .- Rx
    solve!(h.velocity,u,r,bc,bc)
    r .= im .* h.l .* p .- Rz
    solve!(h.velocity,w,r,bc,bc)
    return u,v,w,p
end

function _batchtau!(h::BatchedInfluenceSolver,p,v,dp,Ry)
    B,Ny = size(p)
    p0,v0 = h.responses[5:6]
    @inbounds for s = 1:B
        σ1 = (h.shift[s]*v[s,Ny-1]+dp[s,Ny-1]-Ry[s,Ny-1])/(1-h.sigma[1][s])
        σ2 = (h.shift[s]*v[s,Ny]+dp[s,Ny]-Ry[s,Ny])/(1-h.sigma[2][s])
        for j = 1:Ny
            p[s,j] += (isodd(j) ? σ1 : σ2)*p0[s,j]
            v[s,j] += (isodd(j) ? σ2 : σ1)*v0[s,j]
        end
    end
    return nothing
end
